baseURL = 'https://zoomlion.github.io/'
languageCode = 'en-us'
title = 'zoomlion'

[params]
  description = "A personal blog by zoomlion"
  author = "zoomlion"
  github = "zoomlion"

[taxonomies]
  category = "categories"
  tag = "tags"

[build]
  writeStats = true
